import { radius, spacing, typography } from "./tokens";

// Light theme: "Futurist Serenity" — cream & terracotta
export const lightTheme = {
  colors: {
    background: "#fcf9f4",
    surface: "#fcf9f4",
    surfaceContainer: "#f0ede9",
    surfaceContainerLow: "#f6f3ee",
    surfaceContainerHigh: "#ebe8e3",
    surfaceContainerHighest: "#e5e2dd",
    surfaceContainerLowest: "#ffffff",
    text: "#1c1c19",
    textSecondary: "#54433e",
    primary: "#914731",
    primaryText: "#ffffff",
    primaryContainer: "#af5e47",
    onPrimaryContainer: "#fffbff",
    secondary: "#596244",
    secondaryContainer: "#dee7c0",
    onSecondaryContainer: "#5f6849",
    outline: "#87736d",
    outlineVariant: "#dac1bb",
    border: "#dac1bb",
    error: "#ba1a1a",
    success: "#596244",
    card: "#ebe8e3",
    tabBar: "#fcf9f4",
    tabBarInactive: "#87736d",
    accent: "#914731",
  },
  spacing,
  radius,
  typography,
} as const;

// Dark theme: "Terra Ethos" — deep earthy dark
export const darkTheme = {
  colors: {
    background: "#16130e",
    surface: "#16130e",
    surfaceContainer: "#231f1a",
    surfaceContainerLow: "#1f1b16",
    surfaceContainerHigh: "#2d2924",
    surfaceContainerHighest: "#38342f",
    surfaceContainerLowest: "#110e09",
    text: "#eae1d9",
    textSecondary: "#cec5bc",
    primary: "#ecbe8e",
    primaryText: "#462a06",
    primaryContainer: "#3e2401",
    onPrimaryContainer: "#b1895d",
    secondary: "#bfcab1",
    secondaryContainer: "#404a36",
    onSecondaryContainer: "#aeb9a0",
    outline: "#978f87",
    outlineVariant: "#4b463f",
    border: "#4b463f",
    error: "#ffb4ab",
    success: "#bfcab1",
    card: "#2d2924",
    tabBar: "#1f1b16",
    tabBarInactive: "#cec5bc",
    accent: "#ecbe8e",
  },
  spacing,
  radius,
  typography,
} as const;

export type AppTheme = typeof lightTheme;
