-- Canonical tag taxonomy: 38 keys across 4 facets (theme, meaning, register,
-- occasion). EN labels and descriptions seeded here; ES/DE/FR translations
-- are produced by the pipeline's one-off seed-tag-translations job.

insert into public.tags (key, facet) values
  ('food',          'theme'),
  ('animals',       'theme'),
  ('body',          'theme'),
  ('nature',        'theme'),
  ('weather',       'theme'),
  ('work',          'theme'),
  ('money',         'theme'),
  ('family',        'theme'),
  ('time',          'theme'),
  ('war',           'theme'),
  ('sports',        'theme'),
  ('color',         'theme'),
  ('ease',          'meaning'),
  ('difficulty',    'meaning'),
  ('anger',         'meaning'),
  ('joy',           'meaning'),
  ('sadness',       'meaning'),
  ('surprise',      'meaning'),
  ('love',          'meaning'),
  ('death',         'meaning'),
  ('success',       'meaning'),
  ('failure',       'meaning'),
  ('deception',     'meaning'),
  ('secrecy',       'meaning'),
  ('urgency',       'meaning'),
  ('futility',      'meaning'),
  ('similarity',    'meaning'),
  ('formal',        'register'),
  ('informal',      'register'),
  ('colloquial',    'register'),
  ('vulgar',        'register'),
  ('archaic',       'register'),
  ('greeting',      'occasion'),
  ('farewell',      'occasion'),
  ('encouragement', 'occasion'),
  ('warning',       'occasion'),
  ('advice',        'occasion'),
  ('criticism',     'occasion')
on conflict (key) do nothing;

insert into public.tag_translations (tag_id, language_code, label, description)
select t.id, 'en', v.label, v.description
from public.tags t
join (values
  ('food',          'Food',          'Food, eating, and culinary references.'),
  ('animals',       'Animals',       'Animals, creatures, and zoological imagery.'),
  ('body',          'Body',          'Body parts and physical actions.'),
  ('nature',        'Nature',        'Plants, geography, and the natural world.'),
  ('weather',       'Weather',       'Weather and climatic phenomena.'),
  ('work',          'Work',          'Work, profession, and labor.'),
  ('money',         'Money',         'Money, finance, and material wealth.'),
  ('family',        'Family',        'Family relationships and kinship.'),
  ('time',          'Time',          'Time, schedules, and temporality.'),
  ('war',           'War',           'War, conflict, and military.'),
  ('sports',        'Sports',        'Sports, games, and athletic competition.'),
  ('color',         'Color',         'Colors and visual hues.'),
  ('ease',          'Ease',          'Something simple, easy, or effortless.'),
  ('difficulty',    'Difficulty',    'Something hard, challenging, or troublesome.'),
  ('anger',         'Anger',         'Anger, irritation, or frustration.'),
  ('joy',           'Joy',           'Joy, happiness, or delight.'),
  ('sadness',       'Sadness',       'Sadness, grief, or sorrow.'),
  ('surprise',      'Surprise',      'Surprise or astonishment.'),
  ('love',          'Love',          'Love, affection, or romance.'),
  ('death',         'Death',         'Death, dying, or mortality.'),
  ('success',       'Success',       'Success, achievement, or victory.'),
  ('failure',       'Failure',       'Failure, defeat, or setback.'),
  ('deception',     'Deception',     'Lies, trickery, or false appearance.'),
  ('secrecy',       'Secrecy',       'Secrets or hidden information.'),
  ('urgency',       'Urgency',       'Urgency, haste, or speed.'),
  ('futility',      'Futility',      'Pointlessness or wasted effort.'),
  ('similarity',    'Similarity',    'Comparison or likeness between things.'),
  ('formal',        'Formal',        'Suitable for professional or written contexts.'),
  ('informal',      'Informal',      'Casual, conversational usage.'),
  ('colloquial',    'Colloquial',    'Common in everyday speech.'),
  ('vulgar',        'Vulgar',        'Crude, profane, or impolite.'),
  ('archaic',       'Archaic',       'Outdated or literary, rarely used today.'),
  ('greeting',      'Greeting',      'Used when greeting someone.'),
  ('farewell',      'Farewell',      'Used when saying goodbye.'),
  ('encouragement', 'Encouragement', 'Used to motivate or support.'),
  ('warning',       'Warning',       'Used to warn or caution.'),
  ('advice',        'Advice',        'Used to give counsel or recommendation.'),
  ('criticism',     'Criticism',     'Used to criticize, mock, or rebuke.')
) as v(key, label, description) on v.key = t.key
on conflict (tag_id, language_code) do nothing;
